### ISSUE TITLE
UartBluetoothClient cannot connect to UartBluetoothServer

### ISSUE THREAD

**Issue by BrendanSChang** [sorrir/node-bluetooth#5]
I am trying to run the 'Hello, World!' example in the README with the `UartBluetoothServer` and `UartBluetoothClient`. The server is starting up without issue but I do not see 'SORRIR-Gatt-Server' being advertised and the client is failing with the following error:

```
TypeError: Cannot read property 'connect' of undefined
    at UartBluetoothClient._callee3$ (/home/brendan/standardbots/botman/node_modules/@sorrir/bluetooth/lib/uart/uart-bluetooth-client.js:110:31)
    at tryCatch (/home/brendan/standardbots/botman/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/brendan/standardbots/botman/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/brendan/standardbots/botman/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/brendan/standardbots/botman/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/brendan/standardbots/botman/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

The code is copied exactly from the README:

server.ts
```
import { UartBluetoothServer } from '@sorrir/bluetooth'

async function main() {
  const server = new UartBluetoothServer('SORRIR-Gatt-Server');
  server.handleMessage = (message, sender) => {
      console.log(
          `received: ${JSON.stringify(
              { msg: message, sender: sender })}`);
      server.sendMessage(message);
  };
  await server.start();
}

main();
```

client.ts
```
import { UartBluetoothClient } from '@sorrir/bluetooth'

async function main() {
  const client = new UartBluetoothClient('SORRIR-Gatt-Server');
  client.handleMessage = (message, sender) => {
      console.log(
          `received: ${JSON.stringify(
              { msg: message, sender: sender })}`);
  };
  await client.connect();
  await client.sendMessage('Hello World');
}

main();
```

I am running this on Ubuntu 20.04. Are there any suggestions on how to debug this?

**Comment by QuadratClown** [comment]
Potentially, this could have been caused by a bug in the UartBluetoothClient. I pushed a fix, see https://github.com/sorrir/node-bluetooth/releases/tag/v0.4.1

Please check if this fixes your issue

**Comment by BrendanSChang** [comment]
Thanks for the quick reply. I am now seeing the following error:

```
Error: Client is not yet connected
    at UartBluetoothClient._callee4$ (/home/brendan/standardbots/botman/node_modules/@sorrir/bluetooth/lib/uart/uart-bluetooth-client.js:222:23)
    at tryCatch (/home/brendan/standardbots/botman/node_modules/regenerator-runtime/runtime.js:63:40)
    at Generator.invoke [as _invoke] (/home/brendan/standardbots/botman/node_modules/regenerator-runtime/runtime.js:293:22)
    at Generator.next (/home/brendan/standardbots/botman/node_modules/regenerator-runtime/runtime.js:118:21)
    at asyncGeneratorStep (/home/brendan/standardbots/botman/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/brendan/standardbots/botman/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/brendan/standardbots/botman/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at UartBluetoothClient.<anonymous> (/home/brendan/standardbots/botman/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at UartBluetoothClient.sendMessage (/home/brendan/standardbots/botman/node_modules/@sorrir/bluetooth/lib/uart/uart-bluetooth-client.js:245:29)
```

The output of the server is as follows:
```
/org/bluez/sorrir/advertisement0:GetAll
/:GetManagedObjects
successfully started server
```

The server still appears to be running fine but I don't see 'SORRIR-Gatt-Server' advertised anywhere (e.g. that device is not listed on the discovered devices on my phone). I'm sure that this is the cause of the above issue as well. Is there another way I should test this?

**Comment by QuadratClown** [comment]
What devices are you using as server/client?
What are your Bluez versions?
Have you swapped the server/client roles to see if the advertisements work if the other device is the server instead?

Also, make sure to use a BLE device monitor for your phone to check for Advertisements. If you have Android, I myself use de.kai_morich.serial_bluetooth_terminal

**Comment by QuadratClown** [comment]
Additionally, you can test the connection independently from your code with the command line tool in https://github.com/sorrir/node-bluetooth/blob/master/bin/test-app.js

1. Clone this repo
2. Run `npm install && npm run build`
3. `node bin/test-app.js --server` to start the server on device A
4. `node bin/test-app.js --client` to connect to the server from device B

The two devices should subsequently ping-pong `test`-messages.

**Comment by BrendanSChang** [comment]
Right now, I'm just testing on my laptop (Dell XPS 15 9500) and using my phone (Moto G Power) as a supplementary check. I'll take a look at the serial bluetooth terminal on Android.

I tried running the test-app but the result was unfortunately the same:

server output:
```
$ node bin/test-app.js --server
starting...
role: server
/org/bluez/sorrir/advertisement0:GetAll
/:GetManagedObjects
successfully started server
```

client output:
```
$ node bin/test-app.js --client                                                                                                                                                   
starting...                                                                                                                                                                            
role: client    target: SORRIR-Gatt-Server
connecting to server...
Could not find target device
{ Error: Client is not yet connected
    at UartBluetoothClient._callee4$ (/home/brendan/node-bluetooth/lib/uart/uart-bluetooth-client.js:222:23)
    at tryCatch (/home/brendan/node-bluetooth/node_modules/regenerator-runtime/runtime.js:45:40)
    at Generator.invoke [as _invoke] (/home/brendan/node-bluetooth/node_modules/regenerator-runtime/runtime.js:274:22)
    at Generator.prototype.(anonymous function) [as next] (/home/brendan/node-bluetooth/node_modules/regenerator-runtime/runtime.js:97:21)
    at asyncGeneratorStep (/home/brendan/node-bluetooth/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/home/brendan/node-bluetooth/node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)
    at /home/brendan/node-bluetooth/node_modules/@babel/runtime/helpers/asyncToGenerator.js:32:7
    at new Promise (<anonymous>)
    at UartBluetoothClient.<anonymous> (/home/brendan/node-bluetooth/node_modules/@babel/runtime/helpers/asyncToGenerator.js:21:12)
    at UartBluetoothClient.sendMessage (/home/brendan/node-bluetooth/lib/uart/uart-bluetooth-client.js:245:29)
  description: undefined,
  fileName: undefined,
  lineNumber: undefined,
  endLineNumber: undefined,
  message: 'Client is not yet connected',
  name: 'Error',
  number: undefined }
```

**Comment by QuadratClown** [comment]
I don't quite understand, do you have two laptops? Or are you running this code on only a single device?
You need two different adapters, a adapter cannot connect to itself.

EDIT: Or are you using two different Bluetooth adapters on the same laptop?

**Comment by BrendanSChang** [comment]
Ah, got it, my mistake. I was just testing it with the same laptop because I wasn't seeing the device on my phone or on another laptop using the Web Bluetooth API. I downloaded the Serial Bluetooth Terminal on my phone but I still don't see 'SORRIR-Gatt-Server' as one of the discovered devices.

**Comment by QuadratClown** [comment]
It might be an issue with the adapter and Bluez (or might be the configuration). I had a similar issue on my PC using a Bluetooth dongle - it gave me no error, but no advertisement showed up. Advertisements were not implemented on the driver level.

Which version of Bluez are you using? I'm using 5.53 on a Thinkpad T470 with Ubuntu 20.04 and it works fine. You can check with `bluetoothd -v`.

To see if its indeed a Bluez/adapter issue and you have python installed, you can try the [example-advertisement in the Bluez repository](https://git.kernel.org/pub/scm/bluetooth/bluez.git/plain/test/example-advertisement).

**Comment by BrendanSChang** [comment]
Got it. I'm using Bluez 5.53 on a Dell XPS 15 9500 with Ubuntu 20.04.

```
$ bluetoothd -v
5.53
```

I tried running the example-advertisement and it failed with the following:

```
$ python3 example-advertisement.py 
example-advertisement.py:202: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  mainloop = GObject.MainLoop()
Advertising forever...
GetAll
returning props
Failed to register advertisement: org.bluez.Error.Failed: Failed to parse advertisement.
Traceback (most recent call last):
  File "example-advertisement.py", line 227, in <module>
    main(args.timeout)
  File "example-advertisement.py", line 215, in main
    ad_manager.UnregisterAdvertisement(test_advertisement)
  File "/usr/lib/python3/dist-packages/dbus/proxies.py", line 141, in __call__
    return self._connection.call_blocking(self._named_service,
  File "/usr/lib/python3/dist-packages/dbus/connection.py", line 652, in call_blocking
    reply_message = self.send_message_with_reply_and_block(
dbus.exceptions.DBusException: org.bluez.Error.DoesNotExist: Does Not Exist
```

Thanks for all your help, this is all unfamiliar territory for me. I'm not sure how to proceed.

**Comment by QuadratClown** [comment]
I'm not terribly familiar with this either, but its possible not all the fields that are filled in the advertisement are supported by your adapter. The data field for example is experimental. Try this for the `__init__` function of `TestAdvertisement` instead:
```py
def __init__(self, bus, index):
        Advertisement.__init__(self, bus, index, 'peripheral')
        self.add_local_name('TestAdvertisement')
```

**Comment by BrendanSChang** [comment]
That fixed the issue of the example failing to run. I dug a bit more and determined that the `add_data(...)` line is what's causing the issue. Not sure why that is though.

```
$ python3 example-advertisement.py 
example-advertisement.py:148: PyGIDeprecationWarning: GObject.MainLoop is deprecated; use GLib.MainLoop instead
  mainloop = GObject.MainLoop()
Advertising forever...
GetAll
returning props
Advertisement registered
```

Unfortunately, I still don't see 'TestAdvertisement' anywhere. To be clear, my phone has always been able to detect my laptop on the list of discovered devices, just not any of the test services/advertisements that I've been trying (e.g. 'TestAdvertisement' or 'SORRIR-Gatt-Server'). Do I need to somehow turn off advertising for my laptop as a device in order for this to work?

**Comment by QuadratClown** [comment]
I'm not sure, it's also possible that A) your Bluez installation is misconfigured or B) your adapter (or its driver) does not support advertising in connection with Bluez.

I will close this issue for now, since it's not related to the `@sorrir/bluetooth` package. Hope you can resolve the issue!
